old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
#    producers:
#        # use 'old_sound_rabbit_mq.task_producer' service to send data.
#        task:
#            connection:       default
#            exchange_options: { name: 'task', type: direct }
#    consumers:
#        task:
#            connection:       default
#            exchange_options: { name: 'task', type: direct }
#            queue_options:    { name: 'task'}
#            callback:         App\Consumer\TaskConsumer
    producers:
      github_pr:
        connection: default
        exchange_options: { name: 'github.pr', type: direct }
    consumers:
      github_pr:
        connection: default
        exchange_options: { name: 'github.pr', type: direct}
        queue_options: { name: 'github.pr' }
        idle_timeout: 5
        idle_timeout_exit_code: 0
        callback: App\Consumer\Github\PullRequest