version: "3"
services:
  mbweb:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - mbapp
    networks:
      default:
        aliases:
          - mergebot.docker
    volumes:
      - ..:/var/www/html
    environment:
      - VIRTUAL_HOST=mergebot.docker
      - FPM_HOST=mbapp
  
  mbapp:
    build: ./php72
    links:
      - mbamqp
      - mbdb
    volumes:
      - ~/.composer/cache:/root/.composer/cache
      - ..:/var/www/html
    env_file:
      - ./composer.env
    environment:
      - PHP_IDE_CONFIG=serverName=mergebot.docker
      - XDEBUG_ENABLE=true

  mbamqp:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    volumes:
      - mbrabbitmq-vol:/var/lib/rabbitmq

  mbdb:
    image: mysql:5
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mergebot
      MYSQL_USER: mergebot
      MYSQL_PASSWORD: mergebot
    volumes:
      - mbdb-vol:/data/db

networks:
  default:

volumes:
  mbrabbitmq-vol:
  mbdb-vol: