version: "3"
services:
  mbweb:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - mbapp
    networks:
      default:
        aliases:
          - mergebot.docker
    volumes:
      - ..:/var/www/html
    environment:
      - VIRTUAL_HOST=mergebot.docker
  
  mbapp:
    build: ./php72
    links:
      - mbamqp
    volumes:
      - ~/.composer/cache:/root/.composer/cache
      - ..:/var/www/html
    env_file:
      - ./composer.env
    environment:
      - PHP_IDE_CONFIG=serverName=mergebot.docker
      - XDEBUG_ENABLE=true

  mbamqp:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    volumes:
      - mbrabbitmq-vol:/var/lib/rabbitmq

networks:
  default:

volumes:
  mbrabbitmq-vol: