#index:
#    path: /
#    controller: App\Controller\DefaultController::index

github_webhook:
  path: /github/webhook
  methods:
    - POST
  controller: App\Controller\Github::webhook

event_list:
  path: /secure/event/list
  methods:
    - GET
  controller: App\Controller\Event::list
