#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
  path: /
  methods:
    - GET
  controller: App\Controller\Index\Index::execute

github_webhook:
  path: /github/webhook
  methods:
    - POST
  controller: App\Controller\Github\Webhook::execute

event_list:
  path: /secure/event/list
  methods:
    - GET
  controller: App\Controller\Event\GetList::execute

login:
  path: /login
  methods:
    - POST
  controller: App\Controller\Security\Login::execute
